---
test:
  name: Composer Performance test
  description: This is an example Composer perf test
  clients:
    type: local
    number: 1
  rounds:
  - label: healthcare
    txNumber:
    - 10
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      testAssets: 10
      transaction: GivePermission
    callback: benchmark/composer/composer-samples/healthcare1.js  
  - label: healthcare
    txNumber:
    - 10
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      testAssets: 10
      transaction: RevokePermission
    callback: benchmark/composer/composer-samples/healthcare1.js  
  monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
